name: NSE Option Chain Bot

on:
  schedule:
    # Har 15 minute 3:00 UTC se 10:45 UTC tak (Monday-Friday)
    - cron: '*/15 3-10 * * 1-5'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
        with:
          python-version: '3.11'
      
      - run: pip install requests python-telegram-bot
      
      - run: python bt6.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_oi.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update OI cache [skip ci]"
          git push
